apiVersion: v1
entries:
  inference-caffe:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2019-10-01T11:04:12.118248809Z"
    description: A Helm chart for Kubernetes
    digest: 5a6d73f67ad4bee98e64a9bbc0267456e0ce6370c0980c684712bd71f1b626d8
    name: inference-caffe
    urls:
    -  https://leow1986.github.io/charts/inference-caffe-0.1.0.tgz
    version: 0.1.0
  nginx-0-1-5:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2019-09-25T21:35:49.416377317Z"
    description: A Helm chart for Kubernetes
    digest: 768c234acdac34cb921b3b7c33ee4e6942f9b34f2a03c3367021c31967a1e2db
    name: nginx
    urls:
    - https://leow1986.github.io/charts/nginx-0.1.5.tgz
    version: 0.1.5
generated: "2019-10-01T11:04:12.117831381Z"
